### ISSUE TITLE
Force-replace classnames with other classnames.

### ISSUE THREAD

**Issue by ImperialAlex** [ImperialAlex/XLA_FixedArsenal#16]
raison d'être: 
1. Instead of simply removing tfar_anprc155_<unique_id> radios, replace them with the "base" version.
2. Replace all non-vanilla magazines with vanilla magazines. (Or, post 1.42, with ones of the right magazineGroup).

Problems: Magazines is doable with an array of ["original","replacement"] and a check over the players inventory when he opens the arsenal. However radios would be a massive array (there's a thousand unique id's for each radio). 

Ways to do this:
1. Allow simple 'prefix' matching, e.g. by allowing "*" as a suffix-only wildcard
+ Easy to implement with sqf scriptcommands
- very restrictive, only really handles tfar
2. Add a regexp system
+ very powerful
- hard to implement (even if using a library/external C++ code)
- potentially huge performance impact
- hard to use for people not familiar with regexp

Looking at these, it'll probably be a simply suffix-only wildcard "*" system.

**Comment by nomisum** [comment]
not having to add a new radio whenever accessing the fixed arsenal would be great. still leads to confused players who lost their radio when they access the arsenal for the second time or lost their frequencies by that.

**Comment by ImperialAlex** [comment]
Yeah this is something I really want for my own usecase, too. 
So once performance (#15) is done (it's close to completion) this will be the next feature that I'll be implementing.

**Comment by ImperialAlex** [comment]
I've decided to include this feature for the next release.
While this will delay the release I feel it's necessary to really get the arsenal to a level where whitelisting has no significant negatives.

**Comment by nomisum** [comment]
thats great to hear :+1:
