### ISSUE TITLE
Add support for 'disabling' certain categories(tabs)

### ISSUE THREAD

**Issue by ImperialAlex** [ImperialAlex/XLA_FixedArsenal#2]
Originally submitted by [cuel] (http://forums.bistudio.com/member.php?82563-cuel) on the [BI forums] (http://forums.bistudio.com/showthread.php?184838-quot-Fixed-quot-Arsenal-an-Arsenal-improving-workaround&p=2823906&viewfull=1#post2823906).

>Would it be possible to lock categories ? So someone doesn't press it and lose whatever he has now

**Comment by ImperialAlex** [comment]
Idea: Pass in array of  booleans, each one enabling/disabling a certain tab.
Integrate "allow voice and insignia in non full version"

**Comment by saintblood** [comment]
would be cool but voice and face are not changed global, causing confusion in mp.

havent tried if it would be possible to change face/voice global using BIS_fnc_MP
```
[{_unit setFace "WhiteHead_02";},"BIS_fnc_spawn",true,true] call BIS_fnc_MP;
```
that code is not recommended though small code pieces like that seem to work just fine... never tested with setface in actual mp-session with others though

**Comment by ImperialAlex** [comment]
Oh, thanks for pointing that out! In that case, it might be better to not have the face and voice available. 
Are insignia affected by this, too? I'm pretty sure those seem to work in MP, too.

**Comment by saintblood** [comment]
sorry that it took so long.. had nobody available to take a look at until today..

seems bohemia broke stuff completely... cant set insignia, face or voice using any kind of arsenal.

additional arma does not care when you try to set insignias using
```[this,"111thID"] call BIS_fnc_setUnitInsignia;```

maybe some day they fix it.. then i can take a look into it again

**Comment by ImperialAlex** [comment]
Would be a nice feature but out of scope for current project
