### ISSUE TITLE
Radio deleted on opening arsenal

### ISSUE THREAD

**Issue by Crazy538** [ImperialAlex/XLA_FixedArsenal#30]
Whenever I (or anyone else in my group) accesses arsenal (unrestricted) in MP, the item in their radio slot is removed. To fix this we have to re-open arsenal, select a radio and then come out of it.

Loading a load out removes the radio even if it's included in the load out.

TFR is enabled but this happens with the basic "ItemRadio" from Arma3 as well.

**Comment by ImperialAlex** [comment]
When you say "access unrestricted arsenal", do you mean the vanilla arsenal or my custom arsenal?
The unrestricted arsenal shouldn't be removing things, so there must be more to this story ;)

**Comment by ImperialAlex** [comment]
Closing due to lack of info
