### ISSUE TITLE
Cannot load loadouts with missing mod items

### ISSUE THREAD

**Issue by looterz** [ImperialAlex/XLA_FixedArsenal#32]
This was one of the most useful features of XLA Fixed Arsenal but no longer seems to work correctly.

**Comment by ImperialAlex** [comment]
:( I'll try and reproduce. Are there any (script) error messages?

**Comment by CptFunkymonk** [comment]
Any update on if this issue has been resolved or is close to being resolved? My current group changed our modpack around a bit a now dozens of my loadouts are broken.

http://imgur.com/QhF4rOF

**Comment by ImperialAlex** [comment]
I can't reproduce this (loading partial outfits still works fine for me)
@CptFunkymonk Please note that the picture clearly shows you're using vanilla arsenal (bis_fnc_arsenal) and _not_ my mod (xla_fnc_arsenal). 
My arsenal doesn't have the garage toggle at the top (instead there's a weight bar at the top).
