### ISSUE TITLE
Replacement for Blacklisted Items

### ISSUE THREAD

**Issue by phumberdroz** [ImperialAlex/XLA_FixedArsenal#33]
TFAR changes the classname ones equipped so out of tf_anprc152 gets tf_anprc152_1...256 

maybe we can have something like if classname tf_anprc152_1 is  equipped give tf_anprc152.

Might be able to submit a PR later this week.

**Comment by ImperialAlex** [comment]
Hey! This is already possible, but it takes a tiny bit of setup and it's not a widely known feature.
If you check [this *.sqf file](https://github.com/ImperialAlex/XLA_FixedArsenal/blob/master/addons/XLA_FixedArsenal/missions/showcases/XLA_FixedArsenalExample.Stratis/XLA_arsenal_3CB.sqf) from the sample mission you'll see this at the bottom: 
```
    // TFAR UNIQUE TO GENERIC
    _forceReplace = [];
    _forceReplace resize 1998;
    for [{_i=0}, {_i<999}, {_i=_i+1}] do {
        _forceReplace set [_i, ["tf_anprc152_" + (str (_i+1)), "tf_anprc152"]]; 
        _forceReplace set [_i+999, ["tf_rf7800str_" + (str (_i+1)), "tf_rf7800str"]];            
    };
```

and then later 
`["AmmoboxInit", [_box,false,{true}, _addActionText, false, _forceReplace]] spawn XLA_fnc_arsenal;`

As you can see there's an optional argument to XLA_fnc_arsenal that takes a list of things to replace. See the header comment of [xla_fnc_arsenal](https://github.com/ImperialAlex/XLA_FixedArsenal/blob/master/addons/XLA_FixedArsenal/functions/Inventory/fn_arsenal.sqf) for more details. It will automatically replace any items when the user enters the arsenal as well as automatically doing replacements whenever an outfit is loaded or imported.

**Comment by phumberdroz** [comment]
Well thanks then ! Great work !
