### ISSUE TITLE
ACRE2 Capability issue since ACRE2 2.5

### ISSUE THREAD

**Issue by mgkid3310** [ImperialAlex/XLA_FixedArsenal#34]
Since last ACRE2 update, ACRE2 radios do not show up in XLA arsenal even in full arsenal(they show up in virtual arsenal).
Looks like it's due to using the CBA ItemInfo, so might need some code fix.

**Comment by ImperialAlex** [comment]
Do they show up in the vanilla arsenal? I'm looking into this, but won't be near my gaming rig until Sunday.

**Comment by ImperialAlex** [comment]
As a temporary fix, it should be possible to use the "force-add" feature mentioned here #10

**Comment by mgkid3310** [comment]
As a hotfix, I've made an addon that overrides 'type' and 'simulation' values in ACRE2 items(both under 'ACRE_PRC343' class and one more 'type' under 'ItemInfo' class). Not sure which one was the problem, but one thing sure is that 'scope' wasn't a problem.
According to ACRE2 dev team, there could be some problems with event handlers (ex. 'arsenalOpened'). I don't know much about these, but maybe this could be the problem.

**Comment by ImperialAlex** [comment]
This should be relatively straight-forward to fix, I simply need to emulate the behavior of https://github.com/CBATeam/CBA_A3/blob/master/addons/common/init_addMiscItemsToArsenal.sqf in fn_arsenal 
However, I won't be back until Sunday and even then it might take a few days to get around to this. In the meantime., using the preload force-add should work for people who don't want to override the ACRE classes

**Comment by mgkid3310** [comment]
seems like not working:
if !(isnil "XLA_fnc_addVirtualItemCargo") then {
        [_box, ["%ALL"],true,false] call XLA_fnc_addVirtualItemCargo;
        [_box, _itemsBlacklist, true,false] call XLA_fnc_addVirtualItemBlacklist;
        [_box, ["%ALL"],true,false] call XLA_fnc_addVirtualWeaponCargo;
        [_box, _weaponsBlacklist,true,false] call XLA_fnc_addVirtualWeaponBlacklist;
        [_box, ["%ALL"],true,false] call XLA_fnc_addVirtualBackpackCargo;
        [_box, _backpackBlacklist,true,false] call XLA_fnc_addVirtualBackpackBlacklist;
        [_box, ["%ALL"],true,false] call XLA_fnc_addVirtualMagazineCargo;
        [_box, _magazinesBlacklist,true,false] call XLA_fnc_addVirtualMagazineBlacklist;
        [_box, _radioList, true, false, 1, 1] call XLA_fnc_addVirtualItemCargo; 
        _addActionText = "<t color='#45B6EA'>PX";
        ["Preload",[false,_box,ACE_player,_radioList]] spawn XLA_fnc_arsenal;
        ["AmmoboxInit",[_box,false,{true},_addActionText,false,_forceReplace]] spawn XLA_fnc_arsenal;
    };
I've added preload, but still not showing in arsenal(maybe my code is wrong?)

**Comment by ImperialAlex** [comment]
There are some oddities in your code, e.g. in the last addVirtualItemCargo you probably don't want the last two parameters (the two `1`'s), those aren't part of the public interface, and, in this case, don't make a difference anyway. There's also little point in passing ACE_player into the preload, since equipment currently worn isn't preloaded into the datastructure anyway. 
But, as far as I can tell, nothing should be *wrong*, so maybe my idea of using preload doesn't work in this case :(

**Comment by mgkid3310** [comment]
Thing became bit more serious :(
All other ace items(rangecards, medical items, etc.) are not showing as well.
It seems like due to recent ace patch which changed item types to cba misc items like acre radios.

**Comment by shol9570** [comment]
Same problem with me.
add-force doesn't work.
ace 3.11.0 and ACRE2 2.5 not appear in xla arsenal.

["Preload", [true, objnull, player, _SG_ForceAdd]] spawn xla_fnc_arsenal;

waitUntil {!isNull player};

[_player, true, false, false] call xla_fnc_addVirtualBackpackCargo;
[_player, true, false, false] call xla_fnc_addVirtualItemCargo;
[_player, true, false, false] call xla_fnc_addVirtualMagazineCargo;
[_player, true, false, false] call xla_fnc_addVirtualWeaponCargo;
[_player, _SG_blacklistBackpack, false, false] call xla_fnc_addVirtualBackpackBlacklist;
[_player, _SG_blacklistItem, false, false] call xla_fnc_addVirtualItemBlacklist;
[_player, _SG_blacklistMagazine, false, false] call xla_fnc_addVirtualMagazineBlacklist;
[_player, _SG_blacklistWeapon, false, false] call xla_fnc_addVirtualWeaponBlacklist;

["arsenalLoadingScreen"] call BIS_fnc_endLoadingScreen;

["Open", [false, player, player, false]] spawn xla_fnc_arsenal;

**Comment by shol9570** [comment]
+ I think it maybe has a problem with 'arsenalOpened' event, too.

**Comment by ImperialAlex** [comment]
PR  #35 should have fixed this :)
